---
- name: install tomcat on ubuntu
  hosts: all
  become: yes 
  vars_files:
    - vars/tomcat_ubuntu_vars.yaml    
  tasks:
    - name: install java on ubuntu 
      apt:
         name: openjdk-11-jdk
         update_cache: yes 
         state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: add tomcat user
      user:
        name: tomcat
        home: /opt/tomcat
        group: tomcat
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: download tomcat software
      get_url:
        url: "{{ tomcat_download_source }}"
        dest: "{{ tomcat_download_location }}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: extract tomcat 
      unarchive:
        src: "{{ tomcat_download_location }}"
        dest: "{{ tomcat_install_path }}"
      when: ansible_facts['distribution'] == "Ubuntu"


      
          