---
- name: install tomcat on ubuntu
  hosts: all
  become: yes 
  tasks:
    - name: install java on ubuntu 
      apt:
         name: openjdk-11-jdk
         update_cache: yes 
         state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: add tomcat user
      user:
        name: tomcat
        home: /opt/tomcat
        group: tomcat
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
      
          