---
- name: install tomcat on ubuntu
  hosts: all
  become: yes 
  vars_files:
    - vars/tomcat_ubuntu_vars.yaml    
  tasks:
    - name: install java on ubuntu 
      apt:
         name: "{{ java_package }}"
         update_cache: yes 
         state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: add tomcat group
      group:
        name: "{{ username }}"
        state: present 
    - name: add tomcat user
      user:
        name: "{{ username }}"
        home: /opt/tomcat
        group: "{{ username }}"
        shell: /bin/false
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Unzip package is present
      package:
        name: "{{ unzip_package }}"
        state: present
    - name: download tomcat software
      get_url:
        url: "{{ tomcat_download_source }}"
        dest: "{{ tomcat_download_location }}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: extract tomcat 
      unarchive:
        src: "/tmp/apache-tomcat-10.1.8.zip"
        dest: "{{ tomcat_install_path }}"
      when: ansible_facts['distribution'] == "Ubuntu"
      notify: 
        - create link
    - name: give recursive ownership
      file:
        path: "{{ tomcat_install_path }}"
        recursive: yes
        owner: "{{ username }}"
    - name: give excecutive permission
      file: 
        path: "/opt/tomcat/latest/bin/*.sh"
        mode: "+x"
      loop:
        - /opt/tomcat/latest/bin/catalina.sh
        - /opt/tomcat/latest/bin/ciphers.sh
        - /opt/tomcat/latest/bin/configtest.sh
        - /opt/tomcat/latest/bin/daemon.sh
        - /opt/tomcat/latest/bin/digest.sh
        - /opt/tomcat/latest/bin/makebase.sh
        - /opt/tomcat/latest/bin/migrate.sh
        - /opt/tomcat/latest/bin/setclasspath.sh
        - /opt/tomcat/latest/bin/shutdown.sh
        - /opt/tomcat/latest/bin/startup.sh
        - /opt/tomcat/latest/bin/tool-wrapper.sh
        - /opt/tomcat/latest/bin/version.sh  
  handlers:
    - name: create link
      file:
        src: /opt/tomcat/apache-tomcat-10.1.8
        dest: /opt/tomcat/latest
        owner:  "{{ username }}"
        group: "{{ username }}"
        state: link
      when: ansible_facts['distribution'] == "Ubuntu"


      
          